version: '3.8'

services:
  aether-sync:
    image: ghcr.io/sunday-studio/aether/sync-server:latest
    container_name: aether-sync
    ports:
      - "9999:8080"
    volumes:
      - ./data:/data
    environment:
      - SERVER_SEED_PHRASE=${SERVER_SEED_PHRASE}
    restart: unless-stopped
