-- TODO: Re-enable vector indexes when vector support is needed
-- -- Fix vector indexes: drop broken indexes and recreate only if libsql_vector_idx is available
-- -- This allows the database to work locally without vector indexes while preserving the capability
-- -- when running on Turso Cloud or other libSQL instances with vector support
-- 
-- -- Drop existing vector indexes (they may be broken if libsql_vector_idx was not available)
-- DROP INDEX IF EXISTS entries_embedding_idx;
-- DROP INDEX IF EXISTS tasks_embedding_idx;
-- DROP INDEX IF EXISTS subtasks_embedding_idx;
-- DROP INDEX IF EXISTS goals_embedding_idx;
-- DROP INDEX IF EXISTS tags_embedding_idx;
-- DROP INDEX IF EXISTS bookmarks_embedding_idx;
-- 
-- -- Note: Vector indexes will be recreated automatically by the application
-- -- when it detects that libsql_vector_idx() is available, or they can be
-- -- created manually when connecting to a Turso Cloud instance.
-- -- The embedding columns remain intact, so vector search using vector_distance_cos()
-- -- will still work without the indexes (just slower for large datasets).
