fn main() {
    // Tell Cargo to rerun this build script if these files change
    println!("cargo:rerun-if-changed=src/api/openapi.rs");
    println!("cargo:rerun-if-changed=src/handlers");

    // Note: The OpenAPI spec is generated by running:
    // cargo run --bin generate-openapi
    // This should be run before building the frontend to ensure the spec is up to date

    tauri_build::build()
}
