/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Aether API
 * something, something to write in
 * OpenAPI spec version: 1.0
 */
import type { DbTag } from './db-tag';

export interface DbEntry {
  createdAt?: string;
  document?: string;
  id?: string;
  isArchived?: boolean;
  isDeleted?: boolean;
  isPinned?: boolean;
  tags?: DbTag[];
  updatedAt?: string;
}
