/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Aether API
 * something, something to write in
 * OpenAPI spec version: 1.0
 */

export interface DbTag {
  createdAt?: string;
  id?: string;
  name?: string;
  updatedAt?: string;
}
