/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Aether API
 * something, something to write in
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateEntryPayload {
  date?: string;
  document?: string;
  isArchived?: boolean;
  isDeleted?: boolean;
  isPinned?: boolean;
  tags?: string[];
}
