/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Aether API
 * something, something to write in
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateEntry400,
  CreateEntry500,
  DbEntry,
  DeleteEntryId200,
  DeleteEntryId404,
  DeleteEntryId500,
  GetEntry500,
  GetEntryId404,
  GetEntryId500,
  HandlersCreateEntryPayload,
  PostEntryIdTags400,
  PostEntryIdTags404,
  PostEntryIdTags500,
  UpdateEntry400,
  UpdateEntry404,
  UpdateEntry500
} from './models';





/**
 * Returns all non-deleted entries
 * @summary Get all entries
 */
export type getEntryResponse200 = {
  data: DbEntry[]
  status: 200
}

export type getEntryResponse500 = {
  data: GetEntry500
  status: 500
}
    
export type getEntryResponseSuccess = (getEntryResponse200) & {
  headers: Headers;
};
export type getEntryResponseError = (getEntryResponse500) & {
  headers: Headers;
};

export type getEntryResponse = (getEntryResponseSuccess | getEntryResponseError)

export const getGetEntryUrl = () => {


  

  return `http://nowhere.local:9119/v1/entry`
}

export const getEntry = async ( options?: RequestInit): Promise<getEntryResponse> => {
  
  const res = await fetch(getGetEntryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEntryResponse
}





export const getGetEntryQueryKey = () => {
    return [
    `http://nowhere.local:9119/v1/entry`
    ] as const;
    }

    
export const getGetEntryQueryOptions = <TData = Awaited<ReturnType<typeof getEntry>>, TError = GetEntry500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntry>>> = ({ signal }) => getEntry({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntryQueryResult = NonNullable<Awaited<ReturnType<typeof getEntry>>>
export type GetEntryQueryError = GetEntry500


export function useGetEntry<TData = Awaited<ReturnType<typeof getEntry>>, TError = GetEntry500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntry>>,
          TError,
          Awaited<ReturnType<typeof getEntry>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntry<TData = Awaited<ReturnType<typeof getEntry>>, TError = GetEntry500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntry>>,
          TError,
          Awaited<ReturnType<typeof getEntry>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntry<TData = Awaited<ReturnType<typeof getEntry>>, TError = GetEntry500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all entries
 */

export function useGetEntry<TData = Awaited<ReturnType<typeof getEntry>>, TError = GetEntry500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntry>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Creates a new entry with optional tags
 * @summary Create a new entry
 */
export type createEntryResponse200 = {
  data: DbEntry
  status: 200
}

export type createEntryResponse400 = {
  data: CreateEntry400
  status: 400
}

export type createEntryResponse500 = {
  data: CreateEntry500
  status: 500
}
    
export type createEntryResponseSuccess = (createEntryResponse200) & {
  headers: Headers;
};
export type createEntryResponseError = (createEntryResponse400 | createEntryResponse500) & {
  headers: Headers;
};

export type createEntryResponse = (createEntryResponseSuccess | createEntryResponseError)

export const getCreateEntryUrl = () => {


  

  return `http://nowhere.local:9119/v1/entry`
}

export const createEntry = async (handlersCreateEntryPayload: HandlersCreateEntryPayload, options?: RequestInit): Promise<createEntryResponse> => {
  
  const res = await fetch(getCreateEntryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlersCreateEntryPayload,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createEntryResponse
}




export const getCreateEntryMutationOptions = <TError = CreateEntry400 | CreateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext> => {

const mutationKey = ['createEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEntry>>, {data: HandlersCreateEntryPayload}> = (props) => {
          const {data} = props ?? {};

          return  createEntry(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEntryMutationResult = NonNullable<Awaited<ReturnType<typeof createEntry>>>
    export type CreateEntryMutationBody = HandlersCreateEntryPayload
    export type CreateEntryMutationError = CreateEntry400 | CreateEntry500

    /**
 * @summary Create a new entry
 */
export const useCreateEntry = <TError = CreateEntry400 | CreateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEntry>>,
        TError,
        {data: HandlersCreateEntryPayload},
        TContext
      > => {

      const mutationOptions = getCreateEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns a single entry by its ID
 * @summary Get entry by ID
 */
export type getEntryIdResponse200 = {
  data: DbEntry
  status: 200
}

export type getEntryIdResponse404 = {
  data: GetEntryId404
  status: 404
}

export type getEntryIdResponse500 = {
  data: GetEntryId500
  status: 500
}
    
export type getEntryIdResponseSuccess = (getEntryIdResponse200) & {
  headers: Headers;
};
export type getEntryIdResponseError = (getEntryIdResponse404 | getEntryIdResponse500) & {
  headers: Headers;
};

export type getEntryIdResponse = (getEntryIdResponseSuccess | getEntryIdResponseError)

export const getGetEntryIdUrl = (id: string,) => {


  

  return `http://nowhere.local:9119/v1/entry/${id}`
}

export const getEntryId = async (id: string, options?: RequestInit): Promise<getEntryIdResponse> => {
  
  const res = await fetch(getGetEntryIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getEntryIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEntryIdResponse
}





export const getGetEntryIdQueryKey = (id?: string,) => {
    return [
    `http://nowhere.local:9119/v1/entry/${id}`
    ] as const;
    }

    
export const getGetEntryIdQueryOptions = <TData = Awaited<ReturnType<typeof getEntryId>>, TError = GetEntryId404 | GetEntryId500>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntryIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntryId>>> = ({ signal }) => getEntryId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEntryId>>>
export type GetEntryIdQueryError = GetEntryId404 | GetEntryId500


export function useGetEntryId<TData = Awaited<ReturnType<typeof getEntryId>>, TError = GetEntryId404 | GetEntryId500>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntryId>>,
          TError,
          Awaited<ReturnType<typeof getEntryId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntryId<TData = Awaited<ReturnType<typeof getEntryId>>, TError = GetEntryId404 | GetEntryId500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntryId>>,
          TError,
          Awaited<ReturnType<typeof getEntryId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntryId<TData = Awaited<ReturnType<typeof getEntryId>>, TError = GetEntryId404 | GetEntryId500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get entry by ID
 */

export function useGetEntryId<TData = Awaited<ReturnType<typeof getEntryId>>, TError = GetEntryId404 | GetEntryId500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntryIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update an entry
 */
export type updateEntryResponse200 = {
  data: DbEntry
  status: 200
}

export type updateEntryResponse400 = {
  data: UpdateEntry400
  status: 400
}

export type updateEntryResponse404 = {
  data: UpdateEntry404
  status: 404
}

export type updateEntryResponse500 = {
  data: UpdateEntry500
  status: 500
}
    
export type updateEntryResponseSuccess = (updateEntryResponse200) & {
  headers: Headers;
};
export type updateEntryResponseError = (updateEntryResponse400 | updateEntryResponse404 | updateEntryResponse500) & {
  headers: Headers;
};

export type updateEntryResponse = (updateEntryResponseSuccess | updateEntryResponseError)

export const getUpdateEntryUrl = (id: string,) => {


  

  return `http://nowhere.local:9119/v1/entry/${id}`
}

export const updateEntry = async (id: string,
    handlersCreateEntryPayload: HandlersCreateEntryPayload, options?: RequestInit): Promise<updateEntryResponse> => {
  
  const res = await fetch(getUpdateEntryUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlersCreateEntryPayload,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateEntryResponse
}




export const getUpdateEntryMutationOptions = <TError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext> => {

const mutationKey = ['updateEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEntry>>, {id: string;data: HandlersCreateEntryPayload}> = (props) => {
          const {id,data} = props ?? {};

          return  updateEntry(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEntryMutationResult = NonNullable<Awaited<ReturnType<typeof updateEntry>>>
    export type UpdateEntryMutationBody = HandlersCreateEntryPayload
    export type UpdateEntryMutationError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500

    /**
 * @summary Update an entry
 */
export const useUpdateEntry = <TError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEntry>>,
        TError,
        {id: string;data: HandlersCreateEntryPayload},
        TContext
      > => {

      const mutationOptions = getUpdateEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete an entry (soft delete)
 */
export type deleteEntryIdResponse200 = {
  data: DeleteEntryId200
  status: 200
}

export type deleteEntryIdResponse404 = {
  data: DeleteEntryId404
  status: 404
}

export type deleteEntryIdResponse500 = {
  data: DeleteEntryId500
  status: 500
}
    
export type deleteEntryIdResponseSuccess = (deleteEntryIdResponse200) & {
  headers: Headers;
};
export type deleteEntryIdResponseError = (deleteEntryIdResponse404 | deleteEntryIdResponse500) & {
  headers: Headers;
};

export type deleteEntryIdResponse = (deleteEntryIdResponseSuccess | deleteEntryIdResponseError)

export const getDeleteEntryIdUrl = (id: string,) => {


  

  return `http://nowhere.local:9119/v1/entry/${id}`
}

export const deleteEntryId = async (id: string, options?: RequestInit): Promise<deleteEntryIdResponse> => {
  
  const res = await fetch(getDeleteEntryIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteEntryIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteEntryIdResponse
}




export const getDeleteEntryIdMutationOptions = <TError = DeleteEntryId404 | DeleteEntryId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEntryId>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEntryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteEntryId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEntryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteEntryId(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEntryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEntryId>>>
    
    export type DeleteEntryIdMutationError = DeleteEntryId404 | DeleteEntryId500

    /**
 * @summary Delete an entry (soft delete)
 */
export const useDeleteEntryId = <TError = DeleteEntryId404 | DeleteEntryId500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEntryId>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEntryId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteEntryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Add tags to an entry
 */
export type postEntryIdTagsResponse200 = {
  data: DbEntry
  status: 200
}

export type postEntryIdTagsResponse400 = {
  data: PostEntryIdTags400
  status: 400
}

export type postEntryIdTagsResponse404 = {
  data: PostEntryIdTags404
  status: 404
}

export type postEntryIdTagsResponse500 = {
  data: PostEntryIdTags500
  status: 500
}
    
export type postEntryIdTagsResponseSuccess = (postEntryIdTagsResponse200) & {
  headers: Headers;
};
export type postEntryIdTagsResponseError = (postEntryIdTagsResponse400 | postEntryIdTagsResponse404 | postEntryIdTagsResponse500) & {
  headers: Headers;
};

export type postEntryIdTagsResponse = (postEntryIdTagsResponseSuccess | postEntryIdTagsResponseError)

export const getPostEntryIdTagsUrl = (id: string,) => {


  

  return `http://nowhere.local:9119/v1/entry/${id}/tags`
}

export const postEntryIdTags = async (id: string,
    postEntryIdTagsBody: string[], options?: RequestInit): Promise<postEntryIdTagsResponse> => {
  
  const res = await fetch(getPostEntryIdTagsUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postEntryIdTagsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postEntryIdTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postEntryIdTagsResponse
}




export const getPostEntryIdTagsMutationOptions = <TError = PostEntryIdTags400 | PostEntryIdTags404 | PostEntryIdTags500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEntryIdTags>>, TError,{id: string;data: string[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postEntryIdTags>>, TError,{id: string;data: string[]}, TContext> => {

const mutationKey = ['postEntryIdTags'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEntryIdTags>>, {id: string;data: string[]}> = (props) => {
          const {id,data} = props ?? {};

          return  postEntryIdTags(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEntryIdTagsMutationResult = NonNullable<Awaited<ReturnType<typeof postEntryIdTags>>>
    export type PostEntryIdTagsMutationBody = string[]
    export type PostEntryIdTagsMutationError = PostEntryIdTags400 | PostEntryIdTags404 | PostEntryIdTags500

    /**
 * @summary Add tags to an entry
 */
export const usePostEntryIdTags = <TError = PostEntryIdTags400 | PostEntryIdTags404 | PostEntryIdTags500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEntryIdTags>>, TError,{id: string;data: string[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postEntryIdTags>>,
        TError,
        {id: string;data: string[]},
        TContext
      > => {

      const mutationOptions = getPostEntryIdTagsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
