/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Aether API
 * something, something to write in
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddTagsToEntry400,
  AddTagsToEntry404,
  AddTagsToEntry500,
  CreateEntry400,
  CreateEntry500,
  DbEntry,
  DbTag,
  DeleteEntry200,
  DeleteEntry404,
  DeleteEntry500,
  GetAllTags500,
  GetEntries500,
  GetEntryByID404,
  GetEntryByID500,
  HandlersCreateEntryPayload,
  UpdateEntry400,
  UpdateEntry404,
  UpdateEntry500
} from './models';





/**
 * Returns all non-deleted entries
 * @summary Get all entries
 */
export type getEntriesResponse200 = {
  data: DbEntry[]
  status: 200
}

export type getEntriesResponse500 = {
  data: GetEntries500
  status: 500
}
    
export type getEntriesResponseSuccess = (getEntriesResponse200) & {
  headers: Headers;
};
export type getEntriesResponseError = (getEntriesResponse500) & {
  headers: Headers;
};

export type getEntriesResponse = (getEntriesResponseSuccess | getEntriesResponseError)

export const getGetEntriesUrl = () => {


  

  return `http://127.0.0.1:9119/v1/entry`
}

export const getEntries = async ( options?: RequestInit): Promise<getEntriesResponse> => {
  
  const res = await fetch(getGetEntriesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getEntriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEntriesResponse
}





export const getGetEntriesQueryKey = () => {
    return [
    `http://127.0.0.1:9119/v1/entry`
    ] as const;
    }

    
export const getGetEntriesQueryOptions = <TData = Awaited<ReturnType<typeof getEntries>>, TError = GetEntries500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntries>>> = ({ signal }) => getEntries({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntriesQueryResult = NonNullable<Awaited<ReturnType<typeof getEntries>>>
export type GetEntriesQueryError = GetEntries500


export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = GetEntries500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntries>>,
          TError,
          Awaited<ReturnType<typeof getEntries>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = GetEntries500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntries>>,
          TError,
          Awaited<ReturnType<typeof getEntries>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = GetEntries500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all entries
 */

export function useGetEntries<TData = Awaited<ReturnType<typeof getEntries>>, TError = GetEntries500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntries>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Creates a new entry with optional tags
 * @summary Create a new entry
 */
export type createEntryResponse200 = {
  data: DbEntry
  status: 200
}

export type createEntryResponse400 = {
  data: CreateEntry400
  status: 400
}

export type createEntryResponse500 = {
  data: CreateEntry500
  status: 500
}
    
export type createEntryResponseSuccess = (createEntryResponse200) & {
  headers: Headers;
};
export type createEntryResponseError = (createEntryResponse400 | createEntryResponse500) & {
  headers: Headers;
};

export type createEntryResponse = (createEntryResponseSuccess | createEntryResponseError)

export const getCreateEntryUrl = () => {


  

  return `http://127.0.0.1:9119/v1/entry`
}

export const createEntry = async (handlersCreateEntryPayload: HandlersCreateEntryPayload, options?: RequestInit): Promise<createEntryResponse> => {
  
  const res = await fetch(getCreateEntryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlersCreateEntryPayload,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createEntryResponse
}




export const getCreateEntryMutationOptions = <TError = CreateEntry400 | CreateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext> => {

const mutationKey = ['createEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEntry>>, {data: HandlersCreateEntryPayload}> = (props) => {
          const {data} = props ?? {};

          return  createEntry(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEntryMutationResult = NonNullable<Awaited<ReturnType<typeof createEntry>>>
    export type CreateEntryMutationBody = HandlersCreateEntryPayload
    export type CreateEntryMutationError = CreateEntry400 | CreateEntry500

    /**
 * @summary Create a new entry
 */
export const useCreateEntry = <TError = CreateEntry400 | CreateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEntry>>, TError,{data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEntry>>,
        TError,
        {data: HandlersCreateEntryPayload},
        TContext
      > => {

      const mutationOptions = getCreateEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns a single entry by its ID
 * @summary Get entry by ID
 */
export type getEntryByIDResponse200 = {
  data: DbEntry
  status: 200
}

export type getEntryByIDResponse404 = {
  data: GetEntryByID404
  status: 404
}

export type getEntryByIDResponse500 = {
  data: GetEntryByID500
  status: 500
}
    
export type getEntryByIDResponseSuccess = (getEntryByIDResponse200) & {
  headers: Headers;
};
export type getEntryByIDResponseError = (getEntryByIDResponse404 | getEntryByIDResponse500) & {
  headers: Headers;
};

export type getEntryByIDResponse = (getEntryByIDResponseSuccess | getEntryByIDResponseError)

export const getGetEntryByIDUrl = (id: string,) => {


  

  return `http://127.0.0.1:9119/v1/entry/${id}`
}

export const getEntryByID = async (id: string, options?: RequestInit): Promise<getEntryByIDResponse> => {
  
  const res = await fetch(getGetEntryByIDUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getEntryByIDResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getEntryByIDResponse
}





export const getGetEntryByIDQueryKey = (id?: string,) => {
    return [
    `http://127.0.0.1:9119/v1/entry/${id}`
    ] as const;
    }

    
export const getGetEntryByIDQueryOptions = <TData = Awaited<ReturnType<typeof getEntryByID>>, TError = GetEntryByID404 | GetEntryByID500>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntryByIDQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntryByID>>> = ({ signal }) => getEntryByID(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntryByIDQueryResult = NonNullable<Awaited<ReturnType<typeof getEntryByID>>>
export type GetEntryByIDQueryError = GetEntryByID404 | GetEntryByID500


export function useGetEntryByID<TData = Awaited<ReturnType<typeof getEntryByID>>, TError = GetEntryByID404 | GetEntryByID500>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntryByID>>,
          TError,
          Awaited<ReturnType<typeof getEntryByID>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntryByID<TData = Awaited<ReturnType<typeof getEntryByID>>, TError = GetEntryByID404 | GetEntryByID500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntryByID>>,
          TError,
          Awaited<ReturnType<typeof getEntryByID>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntryByID<TData = Awaited<ReturnType<typeof getEntryByID>>, TError = GetEntryByID404 | GetEntryByID500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get entry by ID
 */

export function useGetEntryByID<TData = Awaited<ReturnType<typeof getEntryByID>>, TError = GetEntryByID404 | GetEntryByID500>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntryByID>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntryByIDQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update an entry
 */
export type updateEntryResponse200 = {
  data: DbEntry
  status: 200
}

export type updateEntryResponse400 = {
  data: UpdateEntry400
  status: 400
}

export type updateEntryResponse404 = {
  data: UpdateEntry404
  status: 404
}

export type updateEntryResponse500 = {
  data: UpdateEntry500
  status: 500
}
    
export type updateEntryResponseSuccess = (updateEntryResponse200) & {
  headers: Headers;
};
export type updateEntryResponseError = (updateEntryResponse400 | updateEntryResponse404 | updateEntryResponse500) & {
  headers: Headers;
};

export type updateEntryResponse = (updateEntryResponseSuccess | updateEntryResponseError)

export const getUpdateEntryUrl = (id: string,) => {


  

  return `http://127.0.0.1:9119/v1/entry/${id}`
}

export const updateEntry = async (id: string,
    handlersCreateEntryPayload: HandlersCreateEntryPayload, options?: RequestInit): Promise<updateEntryResponse> => {
  
  const res = await fetch(getUpdateEntryUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      handlersCreateEntryPayload,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateEntryResponse
}




export const getUpdateEntryMutationOptions = <TError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext> => {

const mutationKey = ['updateEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEntry>>, {id: string;data: HandlersCreateEntryPayload}> = (props) => {
          const {id,data} = props ?? {};

          return  updateEntry(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEntryMutationResult = NonNullable<Awaited<ReturnType<typeof updateEntry>>>
    export type UpdateEntryMutationBody = HandlersCreateEntryPayload
    export type UpdateEntryMutationError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500

    /**
 * @summary Update an entry
 */
export const useUpdateEntry = <TError = UpdateEntry400 | UpdateEntry404 | UpdateEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntry>>, TError,{id: string;data: HandlersCreateEntryPayload}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEntry>>,
        TError,
        {id: string;data: HandlersCreateEntryPayload},
        TContext
      > => {

      const mutationOptions = getUpdateEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete an entry (soft delete)
 */
export type deleteEntryResponse200 = {
  data: DeleteEntry200
  status: 200
}

export type deleteEntryResponse404 = {
  data: DeleteEntry404
  status: 404
}

export type deleteEntryResponse500 = {
  data: DeleteEntry500
  status: 500
}
    
export type deleteEntryResponseSuccess = (deleteEntryResponse200) & {
  headers: Headers;
};
export type deleteEntryResponseError = (deleteEntryResponse404 | deleteEntryResponse500) & {
  headers: Headers;
};

export type deleteEntryResponse = (deleteEntryResponseSuccess | deleteEntryResponseError)

export const getDeleteEntryUrl = (id: string,) => {


  

  return `http://127.0.0.1:9119/v1/entry/${id}`
}

export const deleteEntry = async (id: string, options?: RequestInit): Promise<deleteEntryResponse> => {
  
  const res = await fetch(getDeleteEntryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteEntryResponse
}




export const getDeleteEntryMutationOptions = <TError = DeleteEntry404 | DeleteEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEntry>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEntry>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEntry>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteEntry(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEntryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEntry>>>
    
    export type DeleteEntryMutationError = DeleteEntry404 | DeleteEntry500

    /**
 * @summary Delete an entry (soft delete)
 */
export const useDeleteEntry = <TError = DeleteEntry404 | DeleteEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEntry>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEntry>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Add tags to an entry
 */
export type addTagsToEntryResponse200 = {
  data: DbEntry
  status: 200
}

export type addTagsToEntryResponse400 = {
  data: AddTagsToEntry400
  status: 400
}

export type addTagsToEntryResponse404 = {
  data: AddTagsToEntry404
  status: 404
}

export type addTagsToEntryResponse500 = {
  data: AddTagsToEntry500
  status: 500
}
    
export type addTagsToEntryResponseSuccess = (addTagsToEntryResponse200) & {
  headers: Headers;
};
export type addTagsToEntryResponseError = (addTagsToEntryResponse400 | addTagsToEntryResponse404 | addTagsToEntryResponse500) & {
  headers: Headers;
};

export type addTagsToEntryResponse = (addTagsToEntryResponseSuccess | addTagsToEntryResponseError)

export const getAddTagsToEntryUrl = (id: string,) => {


  

  return `http://127.0.0.1:9119/v1/entry/${id}/tags`
}

export const addTagsToEntry = async (id: string,
    addTagsToEntryBody: string[], options?: RequestInit): Promise<addTagsToEntryResponse> => {
  
  const res = await fetch(getAddTagsToEntryUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addTagsToEntryBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addTagsToEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addTagsToEntryResponse
}




export const getAddTagsToEntryMutationOptions = <TError = AddTagsToEntry400 | AddTagsToEntry404 | AddTagsToEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTagsToEntry>>, TError,{id: string;data: string[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addTagsToEntry>>, TError,{id: string;data: string[]}, TContext> => {

const mutationKey = ['addTagsToEntry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addTagsToEntry>>, {id: string;data: string[]}> = (props) => {
          const {id,data} = props ?? {};

          return  addTagsToEntry(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddTagsToEntryMutationResult = NonNullable<Awaited<ReturnType<typeof addTagsToEntry>>>
    export type AddTagsToEntryMutationBody = string[]
    export type AddTagsToEntryMutationError = AddTagsToEntry400 | AddTagsToEntry404 | AddTagsToEntry500

    /**
 * @summary Add tags to an entry
 */
export const useAddTagsToEntry = <TError = AddTagsToEntry400 | AddTagsToEntry404 | AddTagsToEntry500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTagsToEntry>>, TError,{id: string;data: string[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addTagsToEntry>>,
        TError,
        {id: string;data: string[]},
        TContext
      > => {

      const mutationOptions = getAddTagsToEntryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns all tags
 * @summary Get all tags
 */
export type getAllTagsResponse200 = {
  data: DbTag[]
  status: 200
}

export type getAllTagsResponse500 = {
  data: GetAllTags500
  status: 500
}
    
export type getAllTagsResponseSuccess = (getAllTagsResponse200) & {
  headers: Headers;
};
export type getAllTagsResponseError = (getAllTagsResponse500) & {
  headers: Headers;
};

export type getAllTagsResponse = (getAllTagsResponseSuccess | getAllTagsResponseError)

export const getGetAllTagsUrl = () => {


  

  return `http://127.0.0.1:9119/v1/tags`
}

export const getAllTags = async ( options?: RequestInit): Promise<getAllTagsResponse> => {
  
  const res = await fetch(getGetAllTagsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllTagsResponse
}





export const getGetAllTagsQueryKey = () => {
    return [
    `http://127.0.0.1:9119/v1/tags`
    ] as const;
    }

    
export const getGetAllTagsQueryOptions = <TData = Awaited<ReturnType<typeof getAllTags>>, TError = GetAllTags500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTagsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTags>>> = ({ signal }) => getAllTags({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTags>>>
export type GetAllTagsQueryError = GetAllTags500


export function useGetAllTags<TData = Awaited<ReturnType<typeof getAllTags>>, TError = GetAllTags500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTags>>,
          TError,
          Awaited<ReturnType<typeof getAllTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTags<TData = Awaited<ReturnType<typeof getAllTags>>, TError = GetAllTags500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTags>>,
          TError,
          Awaited<ReturnType<typeof getAllTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTags<TData = Awaited<ReturnType<typeof getAllTags>>, TError = GetAllTags500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all tags
 */

export function useGetAllTags<TData = Awaited<ReturnType<typeof getAllTags>>, TError = GetAllTags500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTagsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





